import pygame

FPS = 100
PLAYER_WIDTH = 35
PLAYER_HEIGHT = 35
PLAYER_VEL = 0
VEL_TERMINAL = 5
GRAVITY = 12 / FPS
OBSTACULO_WIDTH = 35
OBSTACULO_HEIGHT = 35
OBSTACULO_VEL = 5
BALA_WIDTH = 20
BALA_HEIGHT = 10
BALA_VEL = 6