
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import os

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Frame
from main import main


def gui():
    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path("./build/assets/frame0")

    def destruir(lista):
        for elemento in lista:
            elemento.destroy()
    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)

    root = Tk()
    embed = Frame(root, width=1300, height=720)
    embed.pack()
    window = Frame(root, width=1300, height=720)
    window.pack()
    os.environ['SDL_WINDOWID'] = str(embed.winfo_id())


    # The wxPython wiki says you might need the following line on Windows
    # (http://wiki.wxpython.org/IntegratingPyGame).
    os.environ['SDL_VIDEODRIVER'] = 'windib'

    root.update()
    root.geometry("1300x720")
    root.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 720,
        width = 1300,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        960.0,
        540.0,
        image=image_image_1
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=789.0,
        y=929.0,
        width=343.0,
        height=86.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_2 clicked"),
        relief="flat"
    )
    button_2.place(
        x=789.0,
        y=762.0,
        width=343.0,
        height=85.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: (destruir(buttons),main(root)),
        relief="flat"
    )
    button_3.place(
        x=781.0,
        y=429.0,
        width=347.0,
        height=92.0
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("button_4.png"))
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_4 clicked"),
        relief="flat"
    )
    button_4.place(
        x=781.0,
        y=596.0,
        width=360.0,
        height=85.0
    )
    buttons = [button_1,button_2,button_3,button_4]
    root.resizable(True, True)
    root.update()
    root.mainloop()